name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    name: "Build : ${{ matrix.os }}-${{ matrix.compiler }}"
    if: "!contains(github.event.head_commit.message, '[skip CI]')"
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-11-arm, ubuntu-latest, ubuntu-22.04-arm]
        compiler: [llvm]

    env:
      BUILD_DIR: build/${{ matrix.os }}-${{ matrix.compiler }}
      APP_EXT: ${{ contains(matrix.os, 'windows' ) && '.exe' || '' }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1.6.0
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
          vcpkg: false

      - name: Configure CMake
        shell: bash
        run: cmake -S . -B "$BUILD_DIR" -G  "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: bash
        run: cmake --build "${{ env.BUILD_DIR }}"

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: file2cpp-${{ matrix.os }}-${{ matrix.compiler }}
          path: ${{ env.BUILD_DIR }}/file2cpp${{ env.APP_EXT }}
          retention-days: 1
          overwrite: true